-- The whole schema on PostgreSQL. The app ran on H2 until 2026-10 (migrations V1–V12 there);
-- this squashes them for the new database, whose data came over by the one-time H2 import
-- (bzscraper.db.import-h2). Every change from here on is a new migration, V2 onwards.

-- The gig catalog: one row per gig, id = the serialized GigId (date|venue or date|@city).
create table gig (
    id               varchar(255) not null primary key,
    version          bigint       not null default 0,     -- optimistic lock
    title            varchar(255),
    start_date_time  timestamp(6),
    end_date_time    timestamp(6),
    slot_start       timestamp(6),                         -- the band's own slot in a longer event
    slot_end         timestamp(6),
    venue            varchar(255),
    city             varchar(255),
    country          varchar(20),
    street           varchar(255),                         -- where exactly (same-named towns)
    postal_code      varchar(20),
    district         varchar(100),
    region           varchar(100),
    latitude         double precision,
    longitude        double precision,
    lineup           varchar(2000),
    entry_type       varchar(20),
    entry_fee        varchar(255),
    description      varchar(4000),
    facebook_url     varchar(255),
    ticket_url       varchar(255),
    poster_image_url varchar(255),
    cancelled        boolean      not null
);

-- Which gig is published on which platform, under which platform id. No foreign key on
-- purpose: a record outlives its catalog row until deleting the platform copy succeeded.
create table published_gig (
    platform     varchar(40)  not null,
    gig_id       varchar(255) not null,
    external_ref varchar(255),
    primary key (platform, gig_id)
);

-- The sync outbox: platform work queued with the catalog change that needs it (same
-- transaction), run later by the sync worker. Rows are kept as the sync log.
-- gig_id is the serialized GigId (no foreign key: a delete task outlives its gig).
create table sync_task (
    id              bigint generated by default as identity primary key,
    version         bigint        not null default 0,      -- optimistic lock
    gig_id          varchar(255)  not null,
    gig_label       varchar(500)  not null,
    platform        varchar(40)   not null,
    action          varchar(20)   not null,
    status          varchar(20)   not null,
    step            varchar(40),                            -- where a workflow run stands
    attempts        integer       not null,
    created_at      timestamp(6) with time zone not null,
    next_attempt_at timestamp(6) with time zone,
    updated_at      timestamp(6) with time zone not null,
    message         varchar(2000)
);
create index sync_task_status on sync_task (status, next_attempt_at);
create index sync_task_gig on sync_task (gig_id);

-- Each task's history: queued, attempt n, done, failed (with the error), retried, discarded.
create table sync_log (
    id        bigint generated by default as identity primary key,
    task_id   bigint        not null references sync_task (id),
    logged_at timestamp(6) with time zone not null,
    message   varchar(2000) not null
);
create index sync_log_task on sync_log (task_id);

-- Small app settings that must survive a restart (e.g. the sync paused by the user).
create table app_setting (
    name          varchar(100) not null primary key,
    setting_value varchar(1000)
);

-- The band profile: weighted rules that sort calendar events into gigs and the rest.
-- kind / origin are enum names kept as text, so new kinds need no migration.
create table calendar_rule (
    id         bigint generated by default as identity primary key,
    kind       varchar(40)   not null,
    rule_value varchar(1000),
    weight     integer       not null,
    origin     varchar(20)   not null,
    enabled    boolean       not null
);

-- The user's verdict on a calendar event (GIG / NOT_GIG), by the event's stable id.
create table calendar_decision (
    event_uid  varchar(512) not null primary key,
    verdict    varchar(20)  not null,
    decided_at timestamp(6) not null
);

-- The calendar as last read: each read is compared with it to find new, changed and
-- removed events. change_* is what the user hasn't seen yet (null when nothing).
-- notes are the band's private notes (fees, phones): shown in the app only, never published.
create table calendar_event (
    event_uid        varchar(512)  not null primary key,
    title            varchar(2000) not null,
    location         varchar(2000) not null,
    notes            varchar(1000000) not null,
    starts_at        timestamp(6)  not null,
    ends_at          timestamp(6)  not null,
    all_day          boolean       not null,
    repeating        boolean       not null,
    shown_as_free    boolean       not null,
    calendar_status  varchar(20)   not null,
    last_modified    timestamp(6) with time zone,
    suggested        varchar(20)   not null,
    first_seen       timestamp(6) with time zone not null,
    last_seen        timestamp(6) with time zone not null,
    removed_at       timestamp(6) with time zone,
    change_type      varchar(20),
    change_fields    varchar(200),
    suggested_before varchar(20),
    changed_at       timestamp(6) with time zone
);

-- Which catalog gig a calendar event is (gig_id = serialized GigId, re-keyed when an edit
-- changes the gig's identity). No foreign key: a deleted gig leaves a link that matches nothing.
create table calendar_link (
    event_uid varchar(512) not null primary key,
    gig_id    varchar(255) not null,
    linked_at timestamp(6) with time zone not null
);
create index calendar_link_gig on calendar_link (gig_id);
