-- The band profile: weighted rules that sort calendar events into gigs and the rest.
-- kind / origin are enum names kept as text, so new kinds need no migration.
create table calendar_rule (
    id         bigint generated by default as identity primary key,
    kind       varchar(40)   not null,
    rule_value varchar(1000),
    weight     integer       not null,
    origin     varchar(20)   not null,
    enabled    boolean       not null
);

-- The user's verdict on a calendar event (GIG / NOT_GIG), by the event's stable id.
create table calendar_decision (
    event_uid  varchar(512) not null primary key,
    verdict    varchar(20)  not null,
    decided_at timestamp(6) not null
);
