-- The sync outbox: platform work queued with the catalog change that needs it (same
-- transaction), run later by the sync worker. Rows are kept as the sync log.
-- gig_id is the serialized GigId (no foreign key: a delete task outlives its gig).
create table sync_task (
    id              bigint generated by default as identity primary key,
    gig_id          varchar(255)  not null,
    gig_label       varchar(500)  not null,
    platform        varchar(20)   not null,
    action          varchar(20)   not null,
    status          varchar(20)   not null,
    attempts        integer       not null,
    created_at      timestamp(6) with time zone not null,
    next_attempt_at timestamp(6) with time zone,
    updated_at      timestamp(6) with time zone not null,
    message         varchar(2000)
);
create index sync_task_status on sync_task (status, next_attempt_at);
create index sync_task_gig on sync_task (gig_id);

-- Each task's history: queued, attempt n, done, failed (with the error), retried, discarded.
create table sync_log (
    id        bigint generated by default as identity primary key,
    task_id   bigint        not null references sync_task (id),
    logged_at timestamp(6) with time zone not null,
    message   varchar(2000) not null
);
create index sync_log_task on sync_log (task_id);
